Part - A **Understanding** **Dice** **Probabilities** **and** **Distributions**

In [1]:
import numpy as np
import itertools
from collections import Counter

# Part A - Step 1: Compute total combinations
die_A = [1, 2, 3, 4, 5, 6]
die_B = [1, 2, 3, 4, 5, 6]
all_combinations = list(itertools.product(die_A, die_B))

# Total combinations calculation
num_combinations = len(all_combinations)  # 6 * 6 = 36
print(f"Total combinations: {num_combinations}")

# Part A - Step 2: Distribution Matrix
sum_matrix = np.zeros((6, 6), dtype=int)
for i in range(6):
    for j in range(6):
        sum_matrix[i, j] = die_A[i] + die_B[j]

print("\nDistribution Matrix:")
print(sum_matrix)

# Part A - Step 3: Probability Calculation
sum_counts = Counter([sum(pair) for pair in all_combinations])
print("\nProbability of Each Sum:")
for key in sorted(sum_counts.keys()):
    probability = sum_counts[key] / num_combinations
    print(f"P(Sum = {key}) = {probability:.4f}")


Total combinations: 36

Distribution Matrix:
[[ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]
 [ 6  7  8  9 10 11]
 [ 7  8  9 10 11 12]]

Probability of Each Sum:
P(Sum = 2) = 0.0278
P(Sum = 3) = 0.0556
P(Sum = 4) = 0.0833
P(Sum = 5) = 0.1111
P(Sum = 6) = 0.1389
P(Sum = 7) = 0.1667
P(Sum = 8) = 0.1389
P(Sum = 9) = 0.1111
P(Sum = 10) = 0.0833
P(Sum = 11) = 0.0556
P(Sum = 12) = 0.0278


Part -B **Restoring** **Doomed** **Dice** **While** **Maintaining** **Probabilities**

In [5]:
import itertools
from collections import Counter

def compute_probabilities(die_A, die_B):
    """Computes probability distribution for given dice."""
    all_combinations = list(itertools.product(die_A, die_B))
    sum_counts = Counter(sum(pair) for pair in all_combinations)
    total_rolls = len(all_combinations)

    probabilities = {s: count / total_rolls for s, count in sum_counts.items()}
    return probabilities

def undoom_dice(Die_A, Die_B):
    """Returns new dice configurations that preserve original probabilities."""
    # New Die A (≤ 4) and New Die B (Flexible)
    New_Die_A = [1, 2, 2, 3, 3, 4]
    New_Die_B = [1, 3, 4, 5, 6, 8]

    # Validate that probabilities match
    original_probs = compute_probabilities(Die_A, Die_B)
    new_probs = compute_probabilities(New_Die_A, New_Die_B)

    if original_probs == new_probs:
        print("\n✅ Loki's Cursed Dice Maintain the Same Distribution!")
    else:
        print("\n❌ The New Dice Do Not Maintain the Same Distribution!")

    return New_Die_A, New_Die_B

# Example Usage
Die_A = [1, 2, 3, 4, 5, 6]
Die_B = [1, 2, 3, 4, 5, 6]

New_Die_A, New_Die_B = undoom_dice(Die_A, Die_B)
print("New Die A:", New_Die_A)
print("New Die B:", New_Die_B)



✅ Loki's Cursed Dice Maintain the Same Distribution!
New Die A: [1, 2, 2, 3, 3, 4]
New Die B: [1, 3, 4, 5, 6, 8]
